### PR TITLE
Wait for POSIX signals [6371]

### LINKED ISSUE #100: Linux server daemon will enter an infinite-loop, due to polling on stdin for 'q'
Hi all,

I am involved in a project that involves setting up XRCE Agent as a Linux server daemon. Unfortunately, the present version will poll stdin for 'q', which will fail when XRCE Agent runs as a Linux daemon, leaving XRCE Agent printing a never-ending series of "Press 'q' for exit". This happens because stdin is routed to /dev/null by default, when the software is run as a daemon.

I currently have a patch that will change the polling for 'q' to a check for the SIGTERM signal instead, for only the Linux server. SIGTERM is generated when the software is terminated, like when the service is stopped with kill or if the user presses CTRL+C.

I wrote the patch for an earlier version of XRCE-DDS-Agent, before the platform-specific code was moved from microxrce_agent.cpp into other classes. So I will have to update it first. But before I upgrade the patch and make a pull request, I would like to ask if this is the preferred way and if this patch is wanted.

Thanks for your attention!

### PR DESCRIPTION
**Pull request by BorjaOuterelo**
A small improvement of the idea developed in #101 
close #100
close #101

### CODE REVIEW

File: microxrce_agent.cpp [hunk 1]
```diff
@@ -56,13 +69,19 @@ int main(int argc, char** argv)
...
     while ('q' != exit_flag)
     {
         std::cin >> exit_flag;
     }
-
+#else
+    /* Wait for SIGTERM/SIGINT instead, as reading from stdin may be redirected to /dev/null. */
+    int n_signal = 0;
+    sigwait(&signals, &n_signal);
+    std::cout << "signal received: " << n_signal << std::endl;
```
Comment (julianbermudez) [inline microxrce_agent.cpp]: I think this information is not relevant to the user. What do you think?
